aipictors/aipictors

.github/workflows/biome.yaml, biome.json, package.json
=> biomeの最新の機能に追従する

app/[lang]/(main)/works/[work]/_components/copy-work-url.tsx, app/[lang]/(main)/works/[work]/_components/menu-popover.tsx, app/[lang]/(main)/works/[work]/_components/report-dialog.tsx, app/[lang]/(main)/works/[work]/_components/share-on-x.tsx, app/[lang]/(main)/works/[work]/_components/share-popover.tsx, app/[lang]/(main)/works/[work]/_components/work-action.tsx, app/[lang]/(main)/works/[work]/_components/work-article.tsx
=> 報告ボタン他、メニューを修正

app/[lang]/(beta)/_components/beta-header.tsx, app/[lang]/(beta)/_components/beta-navigation-list.tsx, app/[lang]/(beta)/generation/_components/dialogs/generation-terms-dialog.tsx, app/[lang]/(beta)/generation/_components/generation-editor.tsx, app/[lang]/(beta)/generation/_components/generation-submit-button.tsx, app/[lang]/(beta)/layout.tsx, app/[lang]/(main)/_components/home-header.tsx, app/[lang]/(main)/_components/home-navigation-button.tsx, app/[lang]/(main)/_components/home-navigation-list.tsx, app/[lang]/(main)/_components/home-user-navigation-menu.tsx, app/[lang]/(main)/layout.tsx, app/[lang]/_components/login-dialog-button.tsx, app/[lang]/_components/login-dialog.tsx, app/[lang]/_components/logout-dialog-legacy.tsx, app/[lang]/_components/logout-dialog.tsx, app/[lang]/_components/social-login-button.tsx, app/[lang]/account/layout.tsx, app/[lang]/sensitive/layout.tsx, app/[lang]/settings/layout.tsx
このような感じでダイアログを呼び出せるようにした。
```tsx
<LoginDialog>
<LoginDialogButton />
</LoginDialog>
```
画像生成の生成ボタンをログインに切り替えるにはこのようにできると思う。
```
<LoginDialog>
<DialogTrigger>
<Button>{"ログインして生成する"}</Button>
</DialogTrigger>
</LoginDialog>
```
=> ログインのダイアログを修正する

app/[lang]/(beta)/generation/_components/editor-config/generation-editor-config.tsx, app/[lang]/(beta)/generation/_components/generation-editor.tsx
#159
送信時にプロンプトとLoRAモデルの文字列を結合する処理を削除する。プロンプトにLoRA文字列が含まれる仕様になったので。
=> 送信時のプロンプトの内容を修正する

app/[lang]/(beta)/generation/_components/editor-config/generation-editor-config-lora-models.tsx, app/[lang]/(beta)/generation/_components/editor-config/generation-editor-config.tsx, app/[lang]/(beta)/generation/_components/generation-editor.tsx, app/[lang]/(beta)/generation/_components/lora-models-dialog-button.tsx, app/[lang]/(beta)/generation/_hooks/use-image-generation-machine.tsx, app/[lang]/(beta)/generation/_machines/models/__tests__/image-generation-action.test.ts, app/[lang]/(beta)/generation/_machines/models/image-generation-action.ts, app/[lang]/(beta)/generation/_machines/models/image-generation-cache.ts, app/_models/image-generation-config.ts
#159
LoRAの設定をプロンプトから抽出するようにした。
=> LoRAの設定の仕様を変更する

app/[lang]/(beta)/generation/_components/generation-editor-models.tsx, app/[lang]/(beta)/generation/_components/generation-editor-prompt.tsx, app/[lang]/(beta)/generation/_components/generation-editor.tsx, app/[lang]/(beta)/generation/_components/generation-models-button.tsx, app/[lang]/(beta)/generation/_hooks/use-image-generation-machine.tsx, app/[lang]/(beta)/generation/_machines/models/image-generation-action.ts, app/[lang]/(beta)/generation/_machines/models/image-generation-cache.ts
#165 
選択している3つのモデルがローカルストレージに書き込まれて復元されるようになった。新しいモデルを選択した場合は選択中のモデルが上書きされる。
=> モデルの復元機能を追加する

app/[lang]/(beta)/generation/_components/editor-config/generation-editor-config.tsx, app/[lang]/(beta)/generation/_components/generation-editor.tsx, app/[lang]/(beta)/generation/_components/generation-terms-button.tsx
=> エディタの設定の表示を変更してみる

app/[lang]/(beta)/support/chat/_components/dynamic-support-chat-view.tsx, app/[lang]/generation/_components/generation-editor.tsx
=> データ取得の不具合を修正する

app/[lang]/(beta)/_components/beta-navigation-list.tsx, app/[lang]/(beta)/milestones/page.tsx
=> マイルストーンのページを追加する

app/[lang]/generation/_components/editor-submission-view/generation-editor-submit-view.tsx, app/[lang]/generation/_components/editor-task-list-view-view/generation-editor-result-list.tsx, app/[lang]/generation/_components/editor-task-list-view-view/generation-editor-task-list-area.tsx, app/[lang]/generation/_components/editor-task-list-view-view/generation-editor-task-list-view.tsx, app/[lang]/generation/_components/generation-editor.tsx, app/[lang]/generation/_machines/models/__tests__/image-generation-action.test.ts, app/[lang]/generation/_machines/models/image-generation-cache.ts, app/[lang]/generation/tasks/[task]/_components/generation-task-cache-view.tsx, app/[lang]/generation/tasks/_components/generation-task-view-button.tsx
GenerationEditorに定義される変数を減らした。
=> コンポーネント内の関数を整理する

app/[lang]/generation/_components/editor-config-view/generation-editor-config-reset-button.tsx, app/[lang]/generation/_components/editor-config-view/generation-editor-config-seed.tsx, app/[lang]/generation/_components/editor-config-view/generation-editor-config-view.tsx, app/[lang]/generation/_components/editor-submission-view/generation-editor-submit-view-content.tsx, app/[lang]/generation/_components/editor-submission-view/generation-editor-submit-view.tsx, app/[lang]/generation/_components/generation-editor.tsx, app/[lang]/generation/_hooks/use-image-generation-machine.tsx, app/[lang]/generation/_machines/models/image-generation-action.ts, app/[lang]/generation/_machines/models/image-generation-cache.ts, components/app/app-fixed-content.tsx
=> 生成パラメータのリセットボタンを追加、スマホの場合、生成ボタン、ステータスを画面下に固定する、Seedの説明文を改善する

app/[lang]/events/wakiaiai2/page.tsx
=> 和気あいAI2トップ画像変更

app/[lang]/events/wakiaiai2/_assets/event-users.ts, app/[lang]/events/wakiaiai2/page.tsx
=> 和気あいAI情報修正

app/_components/carousel-with-gradation.tsx, app/_components/full-screen-container.tsx, app/_components/like-button.tsx, app/_components/responsive-pagination.tsx, app/routes/($lang)._main._index/_components/home-tag-list.tsx, app/routes/($lang)._main._index/_components/home-tags-section.tsx, app/routes/($lang)._main.posts.$post/_components/work-action-bookmark.tsx, app/routes/($lang)._main.posts.$post/_components/work-image-thumbnail-carousel.tsx
Reverts aipictors/aipictors#551
=> Revert "カラーテーマ rev1 part3 背景色・文字色に合わせる"

.github/workflows/gh-release.yml
なぜGitHub Actionsのデバッグはこんなに面倒なのでしょうか
=> Actionsを元に戻して、修正する

app/routes/($lang)._main.new.animation/route.tsx, app/routes/($lang)._main.new.image/components/success-created-work-dialog.tsx, app/routes/($lang)._main.new.image/route.tsx, app/routes/($lang)._main.new.text/route.tsx, app/routes/($lang)._main.posts.$post.animation.edit._index/route.tsx, app/routes/($lang)._main.posts.$post.image.edit._index/route.tsx, app/routes/($lang)._main.posts.$post.text.edit._index/route.tsx
限定公開作品を投稿、編集した際に表示される成功ダイアログのリンクがおかしいので修正する
=> [fix] 限定公開作品を投稿、編集したときのダイアログの内容を修正

app/components/app/app-contents.tsx, app/components/app/app-page.tsx, app/components/drag/sortable-items.tsx, app/components/responsive-photo-video-works-album.tsx, app/components/responsive-photo-works-album.tsx, app/routes/($lang)._main._index/route.tsx, app/routes/($lang)._main.new.animation/components/post-animation-form-uploader.tsx, app/routes/($lang)._main.new.animation/route.tsx, app/routes/($lang)._main.new.image/components/post-form-header.tsx, app/routes/($lang)._main.new.image/components/post-form-item-draggable-images.tsx, app/routes/($lang)._main.new.image/components/post-form-item-ogp.tsx, app/routes/($lang)._main.new.image/components/post-form-item-video.tsx, app/routes/($lang)._main.new.image/components/post-image-form-uploader.tsx, app/routes/($lang)._main.new.image/components/post-text-form-uploader.tsx, app/routes/($lang)._main.new.image/route.tsx, app/routes/($lang)._main.new.text/route.tsx, app/routes/($lang)._main.posts.$post.animation.edit._index/components/edit-animation-form-uploader.tsx, app/routes/($lang)._main.posts.$post.image.edit._index/components/edit-image-form-uploader.tsx, app/routes/($lang)._main.posts.$post.text.edit._index/components/edit-text-form-uploader.tsx, tailwind.config.ts
1. **投稿画面のフォームのデザイン調整**
- フォームのレイアウトとスタイルを改善し、ユーザーエクスペリエンスを向上させました。
- 入力フィールドの配置やボタンのデザインを調整しました。
2. **全体画面のレイアウト幅を調整**
- レスポンシブデザインの最適化を行い、異なるデバイスでの表示を改善しました。
- ブラウザの幅に応じて適切なレイアウトを提供するように調整しました。
3. **画像容量を減らして速度改善**
- 画像の圧縮技術を使用して、ページの読み込み速度を向上させました。
4. **画像並び替え時のアニメーション改善**
- 画像並び替え時のアニメーションをスムーズにし、ユーザーエクスペリエンスを向上させました。
=> [fix] 投稿画面のフォームのデザイン調整、全体画面のレイアウト幅を調整、画像容量を減らして速度改善、画像並び替え時のアニメーション改善

app/routes/($lang)._main.rankings.$year.$month.weeks.$week._index/route.tsx, app/routes/($lang)._main.rankings._index/components/ranking-header.tsx, app/routes/($lang)._main.rankings._index/components/ranking-work-list.tsx
ウィークリーランキングページを追加
```rankings.$year.$month.weeks.$week._index```
=> [add] ウィークリーランキングページを追加する

app/routes/($lang)._main.rankings._index/route.tsx, app/routes/($lang)._main.themes._index/components/theme-list.tsx, app/routes/($lang)._main.themes._index/route.tsx
=> [add] お題のカレンダーを追加

app/components/responsive-stickers-list.tsx, app/components/sticker-change-access-type-action-dialog.tsx, app/components/sticker-change-access-type-dialog.tsx, app/components/sticker-info-dialog.tsx, app/routes/($lang)._main.posts.$post/components/work-comment-response.tsx, app/routes/($lang)._main.posts.$post/components/work-comment.tsx, app/routes/($lang)._main.stickers.$sticker/components/sticker-article.tsx, app/routes/($lang)._main.stickers.$sticker/route.tsx, app/routes/($lang)._main.stickers._index/components/sticker-list.tsx, app/routes/($lang)._main.stickers._index/route.tsx, app/routes/($lang)._main.users.$user.stickers/components/user-sticker-list.tsx
=> [add] スタンプ個別ページを追加する

app/routes/($lang)._main.rankings._index/components/ranking-sensitive-header.tsx, app/routes/($lang)._main.rankings._index/components/ranking-sensitive-work-list.tsx, app/routes/($lang)._main.sensitive.rankings.$year.$month.weeks.$week._index/route.tsx, app/routes/($lang).events._index/components/events-item.tsx, app/routes/($lang).events._index/components/events-list.tsx, app/routes/($lang).events.wakiaiai-halloween/route.tsx, app/routes/($lang).sensitive.events.$event._index/components/event-sensitive-work-list.tsx, app/routes/($lang).sensitive.events.$event._index/route.tsx, app/routes/($lang).sensitive.events.$event/route.tsx, app/routes/($lang).sensitive.rankings.$year.$month.$day._index/route.tsx, app/routes/($lang).sensitive.rankings.$year.$month._index/route.tsx, app/routes/($lang).sensitive.rankings._index/route.tsx
ランキングとイベントページのセンシティブ切り替え機能追加、新着一覧が新着になっていないバグを修正
=> [fix] ランキングとイベントページのセンシティブ切り替え機能追加、新着一覧が新着になっていないバグを修正

app/routes/events.wakiaiai2/route.tsx, app/routes/events.wakiaiai3/route.tsx
=> 和気あいAI_リスト修正

app/routes/($lang)._main.new.image/components/post-form-item-model.tsx
投稿画面でAIモデルをセレクタから選ぶのが大変なのでフィルターをできるようにする
=> 投稿画面にてAIモデルを選択する際にフィルターをできるようにする

app/routes/($lang)._main.posts.$post._index/components/sensitive-work-article.tsx, app/routes/($lang)._main.posts.$post._index/components/work-sensitive-article-tags.tsx, app/routes/($lang)._main.tags.$tag._index/route.tsx, app/routes/($lang).r.tags.$tag._index/route.tsx
- 作品ページのタグ修正
- タグページの最新作品の取得ロジック修正
=> feat: タグ機能改善

app/routes/($lang)._main._index/components/home-header.tsx, app/routes/($lang)._main._index/components/home-navigation-button.tsx
下記イシューの通り、ヘッダー、メニューのボタンについてTabキーで移動するとき2回移動しなくてよいようにする
https://github.com/aipictors/aipictors/issues/523
=> feat: ヘッダー、メニューのボタンについてTabキーで移動するとき2回移動が必要ないようにする
